### ISSUE TITLE
Check and possibly improve composer support

### ISSUE THREAD

**Issue by jbeyerstedt** [jbeyerstedt/kirby-kirbytag-quote#1]
I just added composer support by reading the documentation only, because I don't use composer myself (I'm a fan of git submodules).
So I need help with:
- [x] validating, that the current package.json file does the right thing (otherwise changing it via a pull request)
- [x] if the composer support was confirmed, adding some lines about installing with composer to the readme.

Thanks in advance for your support.

**Comment by scsskid** [comment]
great plugin! 
I'm not very experienced with composer  as well (or pull requests...), but:
package.json should be composer.json obviously, also try remove trailing comma 
in autoload prop
and licence scheme sytnax should also be diffrent:

https://getcomposer.org/doc/04-schema.md#license

**Comment by jbeyerstedt** [comment]
@scsskid Thanks for the recommendations, I quickly renamed the file and fixes the things you suggested. I also removed the whole autoload section, because the config.php files doesn't even exist any more.
If you use composer, please try again, whether the plugin installation works as expected.

**Comment by scsskid** [comment]
I guess it will work, I published it on packagist, but I got trouble requireing it since its not marked as stable (I guess because code is not in master?)

Nevermind, I'll keep a tracked copy in my repo, it's to time consuming right now, sorry
thanks for the plugin anyways

**Comment by jbeyerstedt** [comment]
I created a new version/ tag for the fixed `composer.json` just now. Do you need to re-trigger packagist to get the new information published?
If far as I understand, this should work now:
```json
"require": {
    "jbeyerstedt/quote": ">2.0"
}
```
Because I didn't find anything saying, that tags must be on the master branch.

Otherwise
```json
"require": {
    "jbeyerstedt/quote": "dev-kirby3"
}
```
should always get you the latest version.


The issue about not using the master branch for current stable code is, that there are breaking changes between the Kirby 2 and Kirby 3 version and I didn't want to break all the links/ git submodules of existing Kirby 2 sites. But whatever you do regarding the branches, it will break somebodies workflow.

**Comment by scsskid** [comment]
great it works, actually I registered the package on packagist, you need an account, I can transfer maintainer status to you

auto update works via git hooks:
https://packagist.org/about#how-to-update-packages
 please add instruction for kirby3 users to Readme:

Get kirby3 version:

```
"require": {
    "jbeyerstedt/quote": "dev-kirby3"
}
```
